### ISSUE TITLE
unhandled error

### ISSUE THREAD

**Issue by holla2040** [agreatfool/swagger-spec-to-pdf#1]
Tried to get this running ubuntu 16.04 64bit today, here's my error

holla@watson[538]: ./node_modules/swagger-spec-to-pdf/bin/swagger2pdf -s swagger.json -o ./dump/
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn /home/holla/api/node_modules/swagger-spec-to-pdf/node_modules/http-server/bin/http-server ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3

any ideas?

**Comment by agreatfool** [comment]
@holla2040 Are you using npm version 3.x?

**Comment by holla2040** [comment]
sorry, I should have included that

holla@watson[502]: node -v
v4.2.6
holla@watson[503]: npm -v
3.5.2

**Comment by agreatfool** [comment]
Gotcha, it's the issue of npm v3 which removed the nested node_modules. Let me think how to fix. Thank you for your issue report.

**Comment by agreatfool** [comment]
Done, please upgrade your local package.

**Comment by holla2040** [comment]
Done, v1.0.3 works great on ubuntu 16.04 64bit.  thanks.
