### ISSUE TITLE
Use yaml file as source instead of JSON

### ISSUE THREAD

**Issue by cabletie** [agreatfool/swagger-spec-to-pdf#10]
I have developed my Swagger source in YAML directly - I'd like to be able to use this tool without having to convert my source to JSON only to have it converted back to YAML prior to being rendered to the PDF.

Can this be done?

**Comment by agreatfool** [comment]
Just fork the repo. And edit file `bin/swagger2pdf`.

And 2 lines:
```javascript
  var specJson = JSON.parse(libFs.readFileSync(src));
  libFs.writeFileSync(libPath.join(editorSpecPath, 'default.yaml'), libYaml.dump(specJson));
```

Remove the first line, and just write your `src yaml` into dest file `default.yaml`, since this tool would only read this file & output pdf by default.

Finally, link your edited version of `swagger2pdf` into your bin path.
