### ISSUE TITLE
Stalled conversion from yaml to pdf

### ISSUE THREAD

**Issue by sammycakes** [agreatfool/swagger-spec-to-pdf#14]
I may just be doing something wrong, but when running "swagger2pdf -y ..."with a yaml doc, an http server starts up, and an Electron window opens, and eventually the command window says "Done.", but no pdf is created in my desired folder. I've left this running for an hour and nothing else happens. Is there something else I should do to continue with the yaml-to-pdf conversion?

I attached an image of my command window.

![image](https://user-images.githubusercontent.com/8474682/58496447-ea97f880-8147-11e9-88ac-0bcfde42a16d.png)

**Comment by agreatfool** [comment]
Hi,

If the command said "Done", that means at least there is no error detected in the process. So it's no need to open the dialogue window any more.

I guess the possible issue is privilege. Maybe you could run this tool as admin privilege, or set your output directory to some place your user has privilege to create file.

Just guess. But you could have a try.

Best Regards

**Comment by sammycakes** [comment]
thanks for your help! my first try as admin wasn't successful but I'll see if I'm just writing to the wrong file name or something silly.

**Comment by zaheershk** [comment]
@sammycakes were you able to get this problem resolved? I'm facing the same and not sure what i'm doing wrong here...any suggestions?
