### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by CLX104** [agreatfool/swagger-spec-to-pdf#3]
I am getting the following error

C:\tryouts\node_modules\swagger-spec-to-pdf>node ./bin/swagger2pdf -s ./swagger-spec-sample.json
Hello thereHello thereevents.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn C:\tryouts\node_modules\swagger-spec-to-pdf\node_modules\.bin\http-server ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

thoughts?

**Comment by agreatfool** [comment]
Did you install it as a global module?

**Comment by CLX104** [comment]
yes I did

npm i -g swagger-spec-to-pdf

cd C:\Users\mural\AppData\Roaming\npm\node_modules\swagger-spec-to-pdf

dir

C:\Users\mural\AppData\Roaming\npm\node_modules\swagger-spec-to-pdf>dir
 Volume in drive C is OS
 Volume Serial Number is E0CE-0D37

 Directory of C:\Users\mural\AppData\Roaming\npm\node_modules\swagger-spec-to-pdf

03/15/2017  10:21 PM    <DIR>          .
03/15/2017  10:21 PM    <DIR>          ..
03/15/2017  10:21 PM               536 .npmignore
03/15/2017  10:21 PM    <DIR>          bin
03/15/2017  10:38 PM    <DIR>          dump
03/15/2017  10:21 PM                 0 index.js
03/15/2017  10:21 PM             1,079 LICENSE
03/15/2017  10:21 PM    <DIR>          node_modules
03/15/2017  10:21 PM             2,336 package.json
03/15/2017  10:21 PM             2,820 README.md
03/15/2017  10:21 PM    <DIR>          src
03/15/2017  10:21 PM    <DIR>          swagger-editor
03/15/2017  10:21 PM            15,300 swagger-spec-sample.json

C:\Users\mural\AppData\Roaming\npm\node_modules\swagger-spec-to-pdf>node ./bin/swagger2pdf -s swagger-spec-sample.json -o ./dump/
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\mural\AppData\Roaming\npm\node_modules\swagger-spec-to-pdf\node_modules\.bin\http-server ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by agreatfool** [comment]
Global installation is not supported currently. Local installation is recommended.
I updated the README document:

### Attention:
Please `DO NOT` install this module as a global module. 
Think this module as a small tool in your project.
Install it locally, and use it locally.
Several bugs related to global installation, and have not been fixed yet.

Please let me know if you have any issue while using this tool as a local module.
